// TODO: clean old placeholders

const LANG_EN = {
  WALLETS_INFO: {
    ADDRESS: 'Address',
    ADDRESS_LOCAL: 'Address local',
    SERVICES: 'Services',
    VERSION: 'Version',
    SUBVERSION: 'Subversion',
    WHITELISTED: 'Whitelisted',
    INBOUND: 'Inbound',
    TIME_OFFSET: 'Time offset',
    PING_TIME: 'Ping time',
    CONNECTION_TIME: 'Connection time',
    LAST_SEND: 'Last send',
    LAST_RECEIVED: 'Last received',
    DATA_SENT: 'Data sent',
    DATA_RECEIVED: 'Data received',
    BAN_SCORE: 'Ban score',
    STARTING_HEIGHT: 'Starting height',
    SYNCED_HEADERS: 'Synced headers',
    SYNCED_BLOCKS: 'Synced blocks',
    NETWORK_TOTALS: 'Network totals',
    TIME: 'Time',
    PEERS: 'Peers',
    LOADING: 'Loading...',
  },
  IMPORT_KEY: {
    IMPORT: 'Import',
    IMPORT_KEY: 'Import key',
    TWO_FORMS_BELOW_P1: 'Two forms below allow you to import either',
    TWO_FORMS_BELOW_P2: 'seed or',
    TWO_FORMS_BELOW_P3: 'key',
    PASSPHRASE: 'Seed',
    NOTICE: 'Notice',
    NOTICE_DESC: 'importing a seed will trigger a full wallet rescan',
    KMD_RESCAN_WARNING_TIME: 'This process can take hours to rescan the whole blockchain',
    SHOW_ADDRESS_AND_WIF: 'Show address and WIF',
    ADDRESS: 'Address',
    OR: 'or',
    TRIGGER_RESCAN: 'Trigger rescan',
    RESCAN_TIP: 'Use this option if you want to trigger rescan after WIF is imported. ' +
                'If you have several addresses that you want to import add them one by one and toggle this option on the last address import.',
    WIF_KEY: 'WIF key',
    IMPORT_AND_RESCAN: 'Import and rescan',
    WIF_DESC: 'Wallet Import Format',
    IMPORT_MULTI_KEYS: 'Import multiple keys',
    IMPORT_MULTI_KEYS_DESC: 'Use this toggle if you want to import several keys at once',
    KEYS_SEPARATED_BY_LINE: 'Keys, separated by a new line',
  },
  CLAIM_INTEREST: {
    ACTUAL_LOCKTIME_SEC: 'Actual time passed since locktime ',
    MONTHLY_CLAIMING_TIP: 'To maximize your rewards claim them once a month.',
    NEED_TO_CLAIM: 'need to claim',
    TIME_SINCE_LOCKTIME: 'Time passed since locktime',
    TIME_TILL_REWARDS_STOP: 'Time until rewards stop accruing',
    SHOW_ZERO_INTEREST: 'Show zero rewards',
    REQ_P1: 'Requirements to accrue rewards',
    REQ_P2: 'spend transaction was at least 1 hour ago, locktime field is set and amount is greater than',
    CLAIM_INTEREST: 'Claim @template@ rewards',
    LOADING: 'Loading rewards data',
    NO_DATA: 'No data',
    TIP: 'Tip',
    NOTICE: 'Notice',
    TIP_DESC: 'don\'t attempt to claim rewards smaller than 0.01 KMD. ' +
              'A fee you have to pay for transaction will be more or equal to the rewards amount.',
    NATIVE_INTEREST_CHANGE_DESC: 'It\'s likely that reward is going to be credited as a separate transaction to a newely created KMD address. ' +
                                 'This is how native implements rewards claiming.',
    LOCKTIME_IS_SET_TO: 'Locktime is set to',
    LOCKTIME_IS_UNSET: 'Locktime is unset! Your UTXO is not accruing rewards.',
    CLAIM_INTEREST_FEE: 'Claim rewards fee',
    SEND_MY_BALANCE_TO: 'Send my balance to',
  },
  ABOUT: {
    AGAMA_WALLET: 'Agama Wallet',
    ABOUT_AGAMA: 'About Agama',
    AGAMA_MODES: 'Agama Wallet is a desktop app that you can use to manage multiple cryptocurrency wallets. ' +
                 'When you set up a wallet, you can configure it to operate in one of the following modes:',
    NATIVE_MODE_DESC: 'Only available for a few currencies. Like \'Full Mode\' but provides advanced functionality.',
    AGAMA_CAPABILITIES: 'Agama includes the following capabilities:',
    BARTER_DEX_DESC: 'Easily exchange cryptocurrencies via a shapeshift-like service.',
    AGAMA_NOTE: 'Note: Agama Wallet is still in development. ' +
                'It is safe to use, but you should make proper backups. ' +
                'We do not recommend using it as the primarily wallet for your cryptocurrencies.',
    TESTERS: 'Testers',
    TESTERS_P1: 'You can help us test Agama. Just',
    TESTERS_P2: 'download and install the latest release',
    TESTERS_P3: 'Then, report any bugs you encounter to our developers on the',
    TESTERS_P4: 'Your help is greatly appreciated!',
    AGAMA_DAPPS: 'Agama also supports the following desktop apps:',
    JUMBLR_DESC: 'A decentralized Bitcoin blockchain tumbler for privacy and lower fees.',
    BARTER_DEX_DESC_ALT: 'A decentralized coin exchange.',
    CHANNEL: 'channel',
    GET_AN_INVITE: 'Get an invite',
    GET_AN_INVITE_P2: 'to our Discord if you\'re not registered yet'
  },
  API: {
    WARNING: 'Warning',
    TX_TOO_LARGE: 'Transaction too large',
    DAEMON_IS_STILL_RUNNING: 'daemon is still running. If you want to completely stop it and remove use stop icon next time.',
    CONN_ERROR: 'Connection error',
    KMD_PASSIVE_ERROR: 'Please make sure to run komodod manually',
    ERROR_SM: 'error',
    ADDRESS_ALREADY_REG: 'Address already registered',
    COULDNT_COPY_ADDRESS: 'Couldn\'t copy address to clipboard',
    COULDNT_CREATE_SEED: 'Couldn\'t create new wallet seed',
    WALLETDAT_MISMATCH: 'Your wallet.dat is not matching the blockchain. Please restart the wallet with -reindex param.',
    PEER_ADDED: 'Peer is added',
    ADDNODE_ALREADY_PENDING: 'Addnode connection was already pending',
    PEER_ALREADY_CONN: 'Peer was already connected',
    ADDNODE_NEEDS_COIN: 'Addnode needs active coin',
    PRIVKEY_IN_WALLET: 'Privkey already in wallet',
    ILLEGAL_PRIVKEY: 'Illegal privkey',
    NO_ACTIVE_COIN: 'No active coin',
    PIN_DECRYPT_ERR: 'Pin decrypt error',
    PIN_MODIFY_ERR: 'Pin modify error',
    ADDRESS_BOOK_MODIFY_ERR: 'Address book modify error',
    // fetch fail errors
    'activeHandle': 'Unable to get coins data',
    'getDexCoins': 'Unable to get coins data',
    'apiElectrumCoins': 'Unable to get coins data',
    'apiElectrumAuth': 'Unable to get auth data',
    'apiElectrumAddCoin': 'Unable to add a coin',
    'apiHerd': 'Unable to add a coin',
    '_apiGetConfig': 'Unable to get daemon config',
    'apiGetConfig': 'Unable to get daemon config',
    'modifyAddressBook': 'Unable to save address book data',
    'getAddressBook': 'Unable to get address book data',
    'apiCli': 'Unable to get CLI data',
    'apiElectrumLock': 'Unable to flush SPV auth data',
    'apiElectrumLogout': 'Unable to end SPV session',
    'apiElectionsLogout': 'Unable to end elections session',
    'apiStopCoind': 'Unable to stop daemon',
    'apiRemoveCoin': 'Unable to remove coin',
    'apiGetCoinList': 'Unable to get coins list',
    'apiPostCoinList': 'Unable to update coins list',
    'apiClearCoindFolder': 'Unable to clear daemon data folder',
    'apiElectrumTransactionsCSV': 'Unable to get transactions history data',
    'apiElectionsTransactions': 'Unable to get transactions history data',
    'apiElectrumTransactions': 'Unable to get transactions history data',
    'apiElectrumTransactionsKV': 'Unable to get transactions history data',
    'apiElectionsBalance': 'Unable to get balance data',
    'apiElectrumBalance': 'Unable to get balance data',
    'apiElectionsStatus': 'Unable to get elections status data',
    'apiElectionsLogin': 'Unable to get elections auth data',
    'apiElectionsSend': 'Unable to update elections data',
    'apiElectionsSendMany': 'Unable to update elections data',
    'apiGetLocalBTCFees': 'Unable to get BTC fees data',
    'apiElectrumSetServer': 'Unable to update SPV server data',
    'apiElectrumCheckServerConnection': 'Unable to update SPV server data',
    'apiElectrumKeys': 'Unable to get SPV auth data',
    'apiElectrumSend': 'Unable to push transaction data',
    'apiElectrumListunspent': 'Unable to get transaction data',
    'apiElectrumBip39Keys': 'Unable to fetch data',
    'apiElectrumKvServersList': 'Unable to get KV data',
    'sendNativeTx': 'Unable to push transaction data',
    'txDataFail': 'Unable to get transaction data',
    'getNewAddress': 'Unable to get new address',
    'setJumblrAddress': 'Unable to set new address',
    'dumpPrivkey': 'Unable to get priv key',
    'importPrivkey': 'Unable to import priv key',
    'validateAddress': 'Unable to validate address',
    'pauseJumblr': 'Unable to pause Jumblr',
    'resumeJumblr': 'Unable to resume Jumblr',
    'getNativePeers': 'Unable to get peers list',
    'getNativeNettotals': 'Unable to get network totals',
    'getSyncInfo': 'Unable to get sync data',
    'encryptKey': 'Unable to get encrypt key data',
    'getSettings': 'Unable to get settings data',
    'getTools': 'Unable to get tools data',
    'getUpdate': 'Unable to get update data',
    'downloadZCashParamsPromise': 'Unable to fetch Zcash params',
    'decryptKey': 'Unable to decrypt data',
    'authError': 'Unable to get auth data',
    'apiElectrumPushTx': 'Unable to push transaction',
    'zmergeToAddressPromise': 'Unable to merge funds',
  },
  NN_ELECTIONS: {
    WRONG_ADDR_FORMAT: 'Wrong address format',
    ADDRESSES: 'Address(es)',
    ADDRESS: 'Address',
    IS_ARE_INVALID: 'is(are) invalid!',
    IS_INVALID: 'is invalid!',
    YOU_SUCCESFULLY_VOTED: 'You succesfully voted',
    FOR: 'for',
    TIME: 'Time',
    REGION: 'Region',
    TO: 'To',
    FROM: 'From',
    NN_ELECTIONS_2018: 'Notary Elections 2018',
    LOGOUT: 'Logout',
    PUB_KEY: 'Pub key',
    LOGIN: 'Login',
    YOU_HAVE: 'You have',
    '4WAY_VOTE': '4-way vote',
    '1WAY_VOTE': '1-way vote',
    ENTER_AN_ADDR: 'Enter an address',
    ENTER_AN_AMOUNT: 'Enter an amout, e.g. 1',
    '25_PERC_SPLIT': 'Each candidate is going to recieve 25% of your VOTE funds',
    ENTER_AN_ADDR_NA: 'Enter an address for NA region',
    ENTER_AN_ADDR_EU: 'Enter an address for EU region',
    ENTER_AN_ADDR_AR: 'Enter an address for AR region',
    ENTER_AN_ADDR_SH: 'Enter an address for SH region',
    VOTE: 'Vote',
    HISTORY: 'History',
  },
  INDEX: {
    Z_ADDR_ONLY: 'Z addresses only chain (ac_private=1).<br>Public addresses are not allowed.',
    TX_DETAILS: 'Transaction details',
    SELF_SM: 'self',
    DEFAULT: 'Default',
    NEW_VERSION: 'New version',
    GENERATING_CSV: 'Generating CSV',
    TX_HISTORY_EXPORT: 'Transaction history export',
    CSV_EXPORT_ERR: 'CSV export error',
    CSV_EXPORT_SAVED: 'CSV export is saved at',
    EXPORT_TO_CSV: 'Export to CSV',
    HIDE_SENSITIVE_DATA: 'Hide sensitive data',
    SHOW_SENSITIVE_DATA: 'Show sensitive data',
    MINING_IS_ENABLED: 'Mining is enabled',
    STAKING_IS_DISABLED: 'Staking is disabled',
    STAKING_IS_ENABLED: 'Staking is enabled',
    LITE_MODE_WATCHONLY: 'You are using watchonly address mode. Send coin functionality is unavailable.',
    MINING_MODE: 'Native / Mining',
    STAKING_MODE: 'Native / Staking',
    QR_CODE: 'QR-code',
    PRICE_PER_1: 'Price per 1',
    SPV_TX_VIN_COUNT_WARN: 'Transaction vin count exceeds max allowed number.<br/>' +
                           'The amount you are seeing now might be not precise.',
    PASSPHRASE_SUCCESSFULLY_ENCRYPTED: 'Seed is encrypted. Please try to login with your password now.',
    PASSPHRASE_SUCCESSFULLY_CHANGED_PIN: 'Seed PIN (@template@.pin) is changed.',
    WALLET_OFFLINE: 'Agama is currently unable to connect to the Internet.',
    OFFLINE: 'Offline',
    TOGGLE_COIN_CONTEXT_MENU: 'Toggle coin context menu',
    TOP_MENU: 'Top menu',
    ERROR_READING: 'Error reading',
    SHOW: 'Show',
    SPV_SERVER_IP: 'Server IP',
    SPV_SERVER_PORT: 'Server Port',
    SPV_SERVER_CON_TYPE: 'Connection type',
    COIND_DOWN_MODAL_ERROR: ' debug.log is empty. Looks like daemon didn\'t start properly. Please retry.',
    SPV_MODE: 'Lite (SPV) Mode',
    PROGRESS_RESCANNING_BLOCKS: '(rescanning blocks)',
    BLOCKS: 'Blocks',
    PLEASE_WAIT_UNTIL_RESCAN_FINISHED: 'Please wait until rescan process is finished',
    VERIFYING_BLOCKS: 'Verifying blocks',
    ALL: 'All',
    NATIVE_ONLY_MODE: 'Native only mode',
    NORMAL_MODE: 'Normal mode',
    T_FUNDS: 'Transparent funds',
    HASH: 'Hash',
    SYNC_IN_PROGRESS: 'Synchronization is in progress',
    UI_UPDATE_DOWNLOADED: 'UI update downloaded. Verifying',
    UI_UPDATED: 'UI is updated!',
    UI_UPDATE_ERROR: 'Error while verifying update file! Please retry again.',
    CHECKING_UI_UPDATE: 'Checking for UI update',
    NEW_UI_UPDATE: 'New UI update available',
    YOU_HAVE_LATEST_UI: 'You have the lastest UI version',
    DOWNLOADING_UI_UPDATE: 'Downloading UI update',
    LAST_50_LINES: 'last 50 lines',
    IS_DOWN: 'is down',
    REINDEX: 'reindex',
    RESCAN: 'rescan',
    BACKGROUND_PROCESS: 'background process',
    NONE: 'none',
    DAEMON_PARAM: 'Daemon param',
    FILTER_BY_ADDRESS: 'Filter by address',
    RESCANNING_LAST_BLOCKS: 'Rescanning last blocks...',
    NO_DATA_AVAILABLE: 'No data available',
    LOADING: 'Loading',
    ACTIVATING_SM: 'activating',
    DL_BLOCKS: 'downloading blocks',
    RESCAN_SM: 'rescanning blocks',
    REINDEX: 'reindexing blocks from disk',
    BLOCKS_SM: 'blocks',
    LOADING_BLOCKS: 'Loading data please wait...',
    WEAK_SEED: 'Weak seed!',
    YOUR_SEED_MUST_CONTAIN: 'Your seed must comply with the following rules:',
    YOUR_SEED_MUST_CONTAIN1: '- at least 1 upper case letter',
    YOUR_SEED_MUST_CONTAIN2: '- at least 1 digit',
    YOUR_SEED_MUST_CONTAIN3: '- at least 1 special character',
    YOUR_SEED_MUST_CONTAIN4: '- minimum 10 characters long',
    YOUR_SEED_MUST_CONTAIN5: '- maximum 100 characters long',
    EXECUTE: 'Execute',
    TYPE_CLI_CMD: 'Type in CLI compatible cmd',
    COIN: 'Coin',
    UPDATE: 'Update',
    UI_UPDATE: 'UI update',
    CHECK_FOR_UPDATE: 'Check for update',
    UPDATE_UI_NOW: 'Update UI now',
    BINS_UPDATE: 'Binaries update',
    UPDATE_BINS_NOW: 'Update binaries now',
    CLI_SELECT_A_COIN: 'Select a coin and type in CLI compatible command',
    CLI_NATIVE_COIN: 'Select native coin',
    IMPORT: 'Import',
    CHECK: 'Check',
    VALIDATE: 'Validate',
    COPY_TO_CLIPBOARD: 'Copy to clipboard',
    EMPTY_DEBUG_LOG: 'Debug.log is empty',
    RESTART: 'Restart',
    WALLET_INFO: 'Wallet Info',
    ADD_COIN: 'Add Coin',
    STOP: 'Stop',
    START: 'Start',
    ACTIVE_ADDRESS: 'active address',
    NO_DATA: 'No history available',
    LOADING_HISTORY: 'Loading transaction history',
    CLOSE: 'Close',
    SHOW: 'Show',
    SHOWING: 'Showing',
    OF: 'of',
    TO_ALT: 'to',
    SEARCH: 'Search',
    PREVIOUS: 'Previous',
    NEXT: 'Next',
    ENTRIES_SM: 'entries',
    SYNC_ERR_BLOCKS: 'Connecting to peers...',
    SELECT_A_COIN: 'Select Coin to add to Agama Wallet',
    WALLETS: 'Wallets',
    ACTIVATE_COIN: 'Activate Coin',
    WELCOME_PLEASE_ADD: 'Welcome. Please add a coin to start.',
    SELECT_SEED_TYPE: 'Please select compatible wallet seed type',
    SELECT: '-Select-',
    SELECT_PIN_NAME: 'Select pin name',
    NATIVE_MODE: 'Native Mode',
    NATIVE_MODE_DESC1: 'This mode is ONLY available for KOMODO and Assetchains. ' +
                        'This mode uses',
    NATIVE_MODE_DESC2: 'to query blockchain data.',
    NATIVE_MODE_DESC3: 'is the only mode which allows you to make',
    NATIVE_MODE_DESC4: 'Z Transactions',
    NATIVE_MODE_DESC5: 'Private Transactions',
    CLOSE: 'Close',
    PLEASE_USE: 'Please use either',
    OR: 'or',
    TO_USE: 'to use',
    WELCOME_LOGIN: 'Welcome. Please login',
    WALLET_SEED: 'Wallet Seed / WIF',
    SIGN_IN: 'Sign in',
    CREATE_WALLET: 'Create new wallet',
    LOGIN_ANOTHER_WALLET: 'Login to another wallet',
    CONFIRM_SEED: 'Confirm Wallet Seed',
    REGISTER: 'Register',
    BACK_TO_LOGIN: 'Back to Login',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_SEARCH: 'Toggle Search',
    TOGGLE_MENUBAR: 'Toggle menubar',
    SETTINGS: 'Settings',
    LOGOUT: 'Logout',
    DASHBOARD: 'Dashboard',
    WALLET_SETTINGS: 'Wallet Settings',
    KMD_WALLET: 'Komodo Wallet',
    ZC_WALLET: 'Zcash Wallet',
    ACTIVE_COINS: 'Active Coins',
    TRANSACTIONS: 'Transactions',
    SEND: 'Send',
    RECEIVE: 'Receive',
    BUNDLES: 'Bundles',
    BALANCES: 'Balances',
    BALANCE: 'Balance',
    VALIDATED: 'Validated',
    NO_WALLET_CAPS: 'NO WALLET SELECTED',
    PLEASE_SELECT_A_WALLET: 'Please select a wallet from active coins list on left',
    ADDRESS: 'Address',
    MY: 'My',
    COPY: 'copy',
    INTEREST_EARNED: 'Rewards Earned',
    TOTAL_BALANCE: 'Total Balance',
    GET_BALANCE: 'Get Balance',
    REFRESH: 'Refresh',
    LIST_UNSPENT: 'List Unspent',
    LIST_TRANSACTIONS: 'List Transactions',
    TRANSACTION_HISTORY: 'Transactions History',
    DIRECTION: 'Direction',
    CONFIRMATIONS: 'Confirmations',
    AMOUNT: 'Amount',
    TIME: 'Time',
    DEST_ADDRESS: 'Dest. Address',
    TX_DETAIL: 'Tx Detail',
    FILL_SEND_FORM: 'Fill Send Form',
    FILL_SEND_DETAILS: 'Fill sending transaction details',
    CONFIRMING: 'Confirming',
    CONFIRM_DETAILS: 'Confirm if details are correct',
    PROCESSING_TX: 'Processing Tx',
    PROCESSING_DETAILS: 'Processing and showing details',
    SEND_FROM: 'Send From',
    SEND_TO: 'Send To',
    FEE: 'Fee',
    FEE_PER_TX: 'Fee (per tx)',
    TOTAL: 'Total',
    AMOUNT_SM: 'amount',
    DONT_SEND: 'Don\'t Send Transaction. Just give me signed transaction bytes.',
    TO: 'To:',
    TX_FEE_REQ: 'Transaction Fee (Required by miners)',
    FROM: 'From:',
    CONFIRM: 'Confirm',
    BACK: 'Back',
    TRANSACTION_RESULT: 'Transaction Result',
    KEY: 'Key',
    VALUE: 'Value',
    INFO: 'Info',
    MAKE_ANOTHER_TX: 'Make Another Transaction',
    RECEIVING_ADDRESS: 'Receiving Addresses',
    TYPE: 'Type',
    INTEREST: 'Rewards',
    ACTIVATING_CHAIN: 'Activating best chain',
    KMD_STARTED: 'Komodo daemon has been started and is processing.<br>' +
                 'Please wait while the best chain is being activated.<br>' +
                 'Tip: in case sync is stuck restart the wallet.',
    CONNECTIONS: 'Connections',
    TRANSPARENT_BALANCE: 'Transparent Balance',
    Z_BALANCE: 'Private (Z) Balance',
    INTEREST_EARNED: 'Rewards Earned',
    ZT_BALANCE: 'Total (Z+T) Balance',
    GET_NEW_ADDRESS: 'Get New Address',
    TRANSPARENT_ADDRESS: 'Transparent Address',
    PRIVATE_Z_ADDRESS: 'Private (Z) Address',
    OPERATIONS_STATUSES: 'Operations Statuses',
    STATUS: 'Status',
    RESULT: 'Result',
    WALLET_INFO: 'Wallet Info',
    WALLET_VERSION: 'Wallet Version',
    UNCONFIRMED_BALANCE: 'Unconfirmed Balance',
    IMMATURE_BALANCE: 'Immature Balance',
    TOTAL_TX_COUNT: 'Total Transactions Count',
    INFO: 'Info',
    VERSION: 'Version',
    PROTOCOL_VERSION: 'Protocol Version',
    NOTARIZED: 'Notarized',
    BLOCKS: 'Blocks',
    DIFFICULTY: 'Difficulty',
    PAY_TX_FEE: 'Pay Transaction Fee',
    RELAY_FEE: 'Relay Fee',
    ERRORS: 'Errors',
    ADD_NODE: 'Add Node',
    USE_THIS_SECTION: 'Use this section to check if the node IP you wish to add is allready active as peer of your coin:',
    SELECT_COIN: 'Select Coin',
    CHECK_NODES: 'Check Nodes',
    USE_THIS_SECTION_PEER: 'Use this section to add a peer IP to a selected coin:',
    WALLET_BACKUP: 'Wallet Backup',
    FIAT_CURRENCY: 'Fiat Currency',
    EXPORT_KEYS: 'Export Keys',
    ONLY_ACTIVE_WIF_KEYS: 'Only the active coin wallet WIF keys will be shown here.<br>' +
                          'You can use these WIF keys to import to another coin wallets.',
    PLEASE_KEEP_KEYS_SAFE: 'Please keep these keys extra safe and secure.',
    PASSPHRASE: 'Seed',
    GET_WIF_KEYS: 'Get WIF Keys',
    IMPORT_KEYS: 'Import Keys',
    IMPORT_KEYS_DESC_P1: 'This section allows you to import KMD/Assetchain private key of all iguana supported coins.',
    IMPORT_KEYS_DESC_P2: 'It is not mandatory to have that coin active in the wallet for which you are executing import private key process.',
    IMPORT_KEYS_DESC_P3: 'You\'ll also notice the private key you imported for one coin or chain will also be showing a new address in all other coin wallets\' receiving address section. ' +
                           'It is normal.',
    INPUT_PRIV_KEY: 'Input Private Key',
    IMPORT_PRIV_KEY: 'Import Private Key',
    EMPTY_PASSPHRASE_FIELD: 'Empty seed field',
    WALLET_RESCAN_FINISHED: 'Wallet rescan is finished',
    ADDRESS_IMPORTED: 'Address imported',
    ADDRESSES_IMPORTED: 'Addresses imported',
    ADDRESS_IMPORTED_RESCAN_IN_PROGRESS: 'Address imported. Wallet rescan is in progress. Please wait until it is finished.',
    ADDRESSES_IMPORTED_RESCAN_IN_PROGRESS: 'Addresses imported. Wallet rescan is in progress. Please wait until it is finished.',
    DEBUG_LOG: 'Debug',
    DEBUG_LOG_DESC: 'This section allows you to read last N lines from debug log file.',
    DEBUG_LOG_LINES: 'Input number of lines to read',
    TARGET: 'Target',
    LOAD_DEBUG_LOG: 'Load debug log',
    REFRESH_FUNDS: 'Refresh Funds',
    INFO: 'Info',
    ENTER: 'Enter',
    ADDR_SM: 'address',
    ACTIVATING: 'Activating',
    QRCODE: 'Show QR code',
    SCAN_QR_CODE: 'Scan QR Code',
    SCAN_QRCODE_WEBCAM: 'Scan QR Code with webcam',
    TOGGLE_ZERO_ADDRESSES: 'Toggle empty addresses',
    NEXT_PAGE: 'Next Page',
    PREVIOUS_PAGE: 'Previous Page',
    CREATE_INVOICE: 'Create Invoice',
    CREATE_INVOICE_QR: 'Create Invoice QR Code',
    QR_CONTENT: 'QR Content',
    CHOOSE_RECEIVING_ADDRESS: 'Choose Address',
    SAVE_AS_IMAGE: 'Save as Image',
    OPEN_TRANSACTION_IN_EPLORER: 'Open transaction in @template@ Explorer',
  },
  ATOMIC: {
    RAW_OUTPUT: 'Raw Output',
    SUBMIT: 'Submit',
    INPUT_PLACEHOLDER: 'addr, txid, blockash etc.',
    SELECT_COMMAND: 'Select Command',
  },
  ADD_COIN: {
    SYNC_ONLY: 'Sync only',
    SAVE_SELECTION: 'Save Selection',
    LOAD_SELECTION: 'Load Selection',
    ACTIVATE_ALL: 'Activate all',
    ADD_ANOTHER_COIN: 'Add another coin',
    ALREADY_ADDED: 'is already added',
    COIN_ALREADY_ADDED: 'Coin already added',
    IN: 'in',
    MODE: 'mode',
    CRYPTO_CURRENCIES: 'Crypto Currencies',
    ASSETCHAINS: 'Assetchains',
    FIAT_CURRENCIES: 'Fiat Currencies',
    LITE: 'Lite',
    LITE_MODE_DESC: 'Lite mode doesn\'t require any blockchain to be loaded locally. ' +
                     'All data is requested on demand from Electrum servers. Lite mode has higher network latency compared to native mode.',
    NONE: 'none (default)',
    STAKING_PUB_P1: 'Provide your seed / WIF key in order to stake.',
    STAKING_PUB_P2: 'If you only want to access funds without staking leave this field blank.',
    MINING_THREADS: 'Mining threads',
  },
  JUMBLR: {
    IMPORTANT_NOTICE: 'Important notice',
    NOTICE_BOTH_NODES: 'You should have both your public and your private node machines running throughout the Jumblr process, with the seed entered and Jumblr activated. ' +
                       'If your private node is not monitoring the private address, you will have to rescan the blockchain to claim your funds.',
    PASSPHRASE: 'Seed',
    PAUSE: 'Pause',
    RESUME: 'Resume',
    STOP: 'Stop',
    TO_SM: 'to',
    ABOUT: 'About Jumblr',
    JUMBLR_FUNCTIONS: 'Jumblr functions all locally which means no middle man is required to jumble your funds. ' +
                      'You take control over the whole process.',
    TIP: 'Tip',
    TIP_DESC: 'to achive maximum anonimity setup Jumblr node on a dedicated piece of hardware (laptop or VPS), use a separate IP address for main Jumblr node',
    PUBLIC_NODE: 'Public node',
    PRIVATE_NODE: 'Private node',
    DEPOSIT_ADDRESS: 'Deposit address',
    SECRET_ADDRESS: 'Secret address',
    DEPOSIT_FUNDS: 'Deposit funds',
    HOW_TO_USE: 'How to use Jumblr',
    CREATE_DEPOSIT_ADDRESS: 'Create deposit address',
    CREATE_SECRET_ADDRESS: 'Create secret address',
    SEND_FUNDS_TO_DEPOSIT: 'Send funds to deposit address',
    PLEASE_WRITE_DOWN_PASSPHRASE: 'Please write down your Jumblr seed and keept it safe.',
    THIS_IS_YOUR_MAIN_RECOVERY: 'This is your main recovery seed.',
    ALL_JUMBLR_ADDRESSES_CAN_BE: 'All Jumblr addresses can be regenrated based on it.',
    DONT_USE_SMART_EDITORS: 'do not use smart editors to store your seed as they tend to add extra characters.<br>' +
                            'This may result in seed mismatch with the original seed.',
    PASSPHRASE_COPIED: 'Seed copied',
    CREATE_JUMBLR_DEPOSIT_ADDRESS: 'Create Jumblr deposit address',
    YOUR_JUMBLR_DEPOSIT_ADDRESS: 'Your Jumblr deposit address',
    JUMBLR_SECRET_DESC_P1: 'Jumblr secret addresses are used for the final z -> t transactions.',
    JUMBLR_SECRET_DESC_P2: 'In order to allow larger accounts to obtain privacy, up to 777 secret addresses are supported.',
    JUMBLR_SECRET_DESC_P3: 'Whenever a z -> t stage is activated, a random secret address from the list of the then active secret addresses is selected.',
    JUMBLR_SECRET_DESC_P4: 'To add a new set of secret addresses enter address count below. The seed below is exactly the same you saw on the previous step.',
    JUMBLR_SECRET_DESC_P5: 'Your Jumblr secret address recovery seed will have the following pattern',
    JUMBLR_SECRET_DESC_P6: 'Where XXX any number from 001 to 777',
    NUMBER_OF_SECRET_ADDR: 'Number of secret addresses',
    CREATE_JUMBLR_SECRET_ADDR: 'Create Jumblr secret address(es)',
    SHOW_ADDRESS_LIST: 'Show address list',
    DEPOSIT_FORM_P1: 'Use the form below to send funds to your jumblr deposit address.',
    DEPOSIT_FORM_P2: 'You can also send funds to deposit address from an external service or another wallet.',
    IMPORT_SECRET_ADDRESS: 'Import secret address',
    CHECK_FUNDS: 'Check funds',
    SECRET_REGEN_DESC_P1: 'Enter your Jumblr seed you got previously during Public node configuration to import secret address.',
    SECRET_REGEN_DESC_P2: 'Seed example',
    SECRET_REGEN_DESC_P3: 'The form below will "regenerate" Jumblr secret address based on seed provided.',
    SECRET_REGEN_DESC_P4: 'After this final step expect to see funds processed and credited to your address after 2 days period.',
    IMPORT_JUMLR_SECRET_ADDRESSES: 'Import Jumblr secret address(es)',
    SHOW_ADDRESS_LIST: 'Show address list',
    NOTICE: 'EXPERIMENTAL TEST VERSION ONLY',
    DESCRIPTION: 'Jumblr feature is very experimental and for now, is Only enabled for testing and debugging. ' +
                 'Please use the current version of Jumblr only with small amounts if you are participating in testing this feature.',
    NEED_NATIVE: 'Need Native Mode Komodo',
    TO_USE_JUMBLR: 'To use Jumblr feature, you need to activate Komodo in Native Mode.',
    IF_YOU_ALREADY_RUNNING: 'If you are already running Komodo in either Basilisk Mode or Full Mode, close the wallet and restart again to start Komodo In Native Mode.',
    THIS_SCREEN_DOESNT_REFRESH: 'This screen does not auto refresh. ' +
                                  'You will need to hit the Refresh button on the top right corner of the screen to get latest Jumblr data.',
    FEW_SECURITY_NOTES: 'Few Security Notes for your Privacy and Anonymity of funds',
    FEW_SECURITY_NOTES_DESC1: 'Jumblr addresses are your Private Addresses.',
    FEW_SECURITY_NOTES_DESC2: 'DO NOT SHARE your Jumblr addresses with anyone.',
    FEW_SECURITY_NOTES_DESC3: 'Jumblr addresses are like YOUR PASSWORD. Keep them safe, secure and hidden.',
    FEW_SECURITY_NOTES_DESC4: 'Only YOU should know your Jumblr Address. Nobody else.',
    FEW_SECURITY_NOTES_DESC5: 'Sharing your Jumblr Addresses with ANYONE will defeat the purpose of using Jumblr, and your funds and transactions will not be private anymore.',
    ACCESS_JUMBLR_FUNDS: 'How to Access your Jumblr Funds',
    ADDRESS_ACCESSIBLE_EASILY: 'Your Jumbler Addresses are accessible easily. For example you logged into your wallet with seed',
    TO_ACCESS: 'To access your Jumbler address funds Logout.',
    START_KMD: 'Start Komodo in either Full Mode or Basilisk Mode.',
    WORD_JUMBLR: 'Then add word \'jumblr \' before your seed.',
    SMALL_LETTERS: '"jumblr" is all in small letters.',
    WHITE_SPACE: 'There is a white space after "jumblr ".',
    PER_EXAMPLE: 'So as per this example, your Jumbler Addresses are accessible with:',
    LOGIN_WITH_JUMBLR: 'You\'ll login with your Jumblr seed to access funds and will be able to use it just like any other wallet address.',
    AGAIN_DONT_SHARE: 'Again, DO NOT SHARE YOUR JUMBLR ADDRESS WITH ANYONE.',
    USING_JUMBLR: 'Using Jumblr',
    RUN_KMD: 'Run Komodo in Native Mode',
    LOGIN_KMD: 'Login with your seed',
    GO_TO: 'Go to Jumblr Menu',
    FIND_DEPOSIT_ADDR: 'There find your Deposit Address for coin you want to anonymise your funds. (For a start only KMD is supported. BTC support will come in later versions)',
    YOU_SEND_FUNDS: 'You send your funds to deposit address.',
    KEEP_WALLET_OPEN: 'Keep your wallet open',
    IMPORTANT_FUNDS: '[IMPORTANT] Funds are processed in lot sizes 10 KMD, 100 KMD, 1000 KMD, and 10,000 KMD.',
    LARGE_LOT: 'The large lot sizes will process first, and then smaller.',
    EG: 'For example, you sent 1393 KMD to KMD Deposit Address.<br>' +
        'First it will process 1000 KMD<br>' +
        'then 100 KMD<br>' +
        'then 100 KMD<br>' +
        'then 100 KMD',
    '93_KMD': '93 KMD will keep waiting in deposit address.',
    TO_CLEAR_THEM: 'To clear them you\'ll have to send 7 KMD more to your KMD Deposit Address.',
    WHEN_IT_TOTALS: 'When it totals to 10/100/1000 KMD, it will process to your KMD Jumblr Address.',
    JADDR: 'Jumblr Addresses',
    BTC_DEPOSIT: 'BTC Deposit',
    SHOW_HIDE: 'Show/Hide',
    HIDDEN: 'Hidden for security reason.',
    KMD_DEPOSIT: 'KMD Deposit',
    JSTATUS: 'Jumblr Status',
    RESULT: 'Result',
    DEPOSITED: 'Deposited',
    PUB_TO_PRIV: 'Public to Private',
    PRIV_TO_PRIV: 'Private to Private',
    PRIV_TO_PUB: 'Private to Public',
    FINISHED: 'Finished',
    PENDING: 'Pending',
    ERROR: 'Error',
  },
  RECEIVE: {
    TOOGLE_ADDRESS: 'Toggle address context menu',
    PUB_KEY: 'pub key',
    Z_KEY: 'z address',
    PRIV_KEY: 'priv key (WIF)',
    VALIDATE_ADDRESS: 'validate address',
    YOU_DONT_OWN_PRIV_KEYS: 'You don\'t own priv keys for this address',
    AVAIL_AMOUNT_TO_SPEND_0: 'Available amount to spend: 0',
    DISPLAY_ALL_ADDR: 'Display all addresses including not mine (ismine:false)',
  },
  DASHBOARD: {
    NA: 'N/A',
    KMD_UTXO_ISSUES: 'One or several of your UTXO are not generating rewards.<br>This could happen either if utxo size is less than 10 KMD, locktime field is not set or last time you claimed was over a month ago.<br>Please click on "Claim now" button to see details.',
    SHOW_ALL_ADDR: 'Show all addresses',
    RPC_CONN_FAILURE: 'Unable to establish RPC connection!<br>Retries count',
    REMOVE: 'Remove',
    STOP: 'Stop',
    STOP_ALL: 'Stop all',
    SOFT_LOGOUT: 'Soft logout',
    COMPLETE_LOGOUT: 'Complete logout',
    GENERATE_SM: 'generate',
    RECEIVE_ADDR_COPIED: 'address copied to clipboard',
    SERVER_SM: 'server',
    IS_UNREACHABLE: 'is unreachable',
    SERVER_SET_TO: 'server is set to',
    SPV_AUTO_SWITCH: 'Trying to switch to another server',
    HOW_TO_SWITCH_MANUALLY: 'How to switch manually',
    SELECT_ADDRESS: '- Select Address -',
    SEND_TOADDR_REQ: 'To Address is required.',
    SEND_FROMADDR_REQ: 'From Address is required.',
    SEND_AMOUNT_REQ: 'Please enter amount to send.',
    SEND_FEE_REQ: 'Make sure you have fee entered. Default value is',
    SEND_TOTAL_REQ: 'Make sure you have both amount and fee entered to calculate final total.',
    SEND_TX_PROGRESS: 'The transaction submitted is processing. Once processed the transaction details will be displayed here.',
    SUBTRACT_FEE: 'Subtract fee from amount',
    UNKNOWN: 'Unknown',
    IN: 'IN',
    OUT: 'OUT',
    MINED: 'Mined',
    IMMATURE: 'Immature',
    ZADDR_NOT_LISTED: 'Address not listed by wallet',
    ADDR_COPIED: 'Address Copied',
    QR_ERR_NO_VIDEO_DEVICE: 'Error: no video input devices found!',
    QR_ERR_UNKNOWN: 'Error: unknown error!',
    SPV_CONN_ERROR: 'Connection error!',
    SPV_CONN_ERROR_P1: 'Go to "Settings", select "SPV Server List" tab, choose new server and click "OK".',
    FAILED_TX_INFO: 'Transaction failed or blocks reindexing is in progress. ' +
                    'Failed transactions usually rejected after a while resulting in your funds being credited back.',
    SPV_CLAIMED_INTEREST: 'Claimed rewards',
    CLAIM_INTEREST_HELPER_BAR_P1: 'You have',
    CLAIM_INTEREST_HELPER_BAR_P2: 'to claim',
    CLAIM_INTEREST_HELPER_BAR_P3: 'Claim now',
    CLAIM_INTEREST_HELPER_BAR_ALT_P1: 'You don\'t have any rewards to claim',
    CLAIM_INTEREST_HELPER_BAR_ALT_P2: 'Check UTXO',
    SEARCH: 'Search',
    WIN_SYNC_WORKAROUND_APPLIED: 'Windows sync workaround is applied. Closing the app...',
    WIN_SYNC_WORKAROUND_APPLY_FAILED: 'Unable to apply Windows sync workaround!',
    WIN_SYNC_WORKAROUND_REVERTED: 'Current sync state reached 80% level. Windows sync workaround is disabled. Changes will be applied next time you start the app.',
    WIN_SYNC_WORKAROUND_CTA_P1: 'Slow sync speed on Windows? Try this workaround.',
    WIN_SYNC_WORKAROUND_CTA_P2: 'It will add maxconnections=1 in komodo.conf file and force close the app.',
    WIN_SYNC_WORKAROUND_CTA_P3: 'Please run the app again after that.',
    APPLY_WORKAROUND: 'Apply workaround',
    CURRENT_BLOCK_SM: 'current block',
  },
  TOASTR: {
    INCORRECT_WIF: 'Incorrect WIF key format',
    ERROR: 'Error',
    FAILED_TO_VERIFY_ADDR: 'Failed to verify address',
    COIN_UNABLE_TO_STOP: 'Unable to stop @template@. Try again.',
    COIN_IS_STOPPED: 'is stopped',
    COIN_IS_REMOVED: 'is removed',
    JUMBLR_RESUMED: 'Jumblr resumed',
    JUMBLR_PAUSED: 'Jumblr paused',
    DATADIR_UNABLE_TO_CLEAR: 'Unable to clear',
    DATADIR_CLEARED: 'data folder is cleared',
    PORT_IS_TAKEN: 'Port @template@ is already taken!',
    ERROR_STARTING_DAEMON: 'Error starting @template@ daemon.',
    KOMODO_DATADIR_INVALID: 'Komodo datadir path is invalid.<br>' +
                            'It must be an absolute path to an existing folder that doesn\'t contain spaces and/or any special characters.',
    KOMODO_DATADIR_NOT_DIR: 'Komodo datadir path is not a directory.<br>' +
                            'It must be an absolute path to an existing folder that doesn\'t contain spaces and/or any special characters.',
    INVALID_ADDRESS: 'Invalid @template@ address',
    RESTART_AGAMA_WITH_REINDEX_PARAM: 'Restart Agama and run Komodo with -reindex param',
    JUMBLR_DEPOSIT_ADDRESS_SET: 'Jumblr deposit address is set',
    JUMBLR_SECRET_ADDRESSES_IMPORTED: 'Jumblr secret addresses imported',
    JUMBLR_SECRET_ADDRESS_IMPORTED: 'Jumblr secret address imported',
    JUMBLR_WRONG_PASSPHRASE: 'Provided seed has wrong format',
    JUMBLR_SECRET_ADDRESS_SET: 'Jumblr secret address is set',
    JUMBLR_SECRET_ADDRESSES_SET: 'Jumblr secret addresses are set',
    ENTER_CORRECT_ADDR_COUNT: 'Enter a correct address count value',
    TXID_COPIED: 'Transaction ID copied',
    CLAIM_INTEREST_BALANCE_SENT_P1: 'Your full balance is sent to address',
    CLAIM_INTEREST_BALANCE_SENT_P2: 'Check back your new balance in a few minutes.',
    SETTINGS_RESET: 'Settings are reset to default',
    SETTINGS_SAVED: 'Settings are saved',
    SETTINGS_CACHE_RESET: 'SPV cache is cleared',
    TRANSACTION_FAILED: 'Transaction failed',
    WALLET_NOTIFICATION: 'Wallet Notification',
    ACCOUNT_NOTIFICATION: 'Account Notification',
    COIN_NOTIFICATION: 'Coin Notification',
    TX_NOTIFICATION: 'Transaction Notification',
    SERVICE_NOTIFICATION: 'Service Notification',
    LOGIN_NOTIFICATION: 'Login Notification',
    SETTINGS_NOTIFICATION: 'Settings Notification',
    RECADDR_UPDATED: 'Receiving Address list updated',
    SWITCHED_TO: 'switched to',
    MODE: 'Mode',
    TX_SENT: 'Transaction Sent',
    TX_SEND_ERR: 'Unable to complete transaction',
    LOOKS_LIKE: 'Looks like',
    ALREADY_RUNNING: 'already running',
    STARTED_IN: 'started in',
    KOMODO_ERR: 'Unable to start Komodod',
    SIGNED_TX_GENERATED: 'Signed transaction generated',
    SIGNED_TX_GENERATED_FAIL: 'Signed transaction Failed to generate',
    SENDING_TX: 'Sending Transaction to Network',
    SIGNED_TX_SENT: 'Signed transaction sent successfully',
    GETTING_TXID_INFO: 'Getting txid info for updating funds data',
    REFRESHING_FUNDS: 'Refreshing Wallet Funds',
    TX_FAILED: 'Sent Transaction failed. Please check send Transaction page for details.',
    TX_SENT_ALT: 'Transaction sent successfully. Check Operation Statuses section for details below. It may take sometime for it to appear on your screen.',
    COIN_STARTED: 'coin started',
    ADDR_ALREADY_REG: 'address already registered on network.',
    REG: 'Registered',
    REG_ADDR: 'address on network.',
    REG_ADDR_FAILED: 'address Registeration failed. Please try again.',
    INVALID_QUERY: 'Invalid query sent for',
    TRY_AGAIN: 'Please try again.',
    ADDR_ISNT_REG: 'Address isn\'t Registered on Network. Please Register',
    INVALID_QUERY_ALT: 'Invalid query sent. Please try again.',
    VALIDATION_SUCCESS: 'Validation Success on Network',
    KMD_NATIVE_CON_ERROR: 'Connection Error. Is external wallet running?',
    LOGIN_SUCCESSFULL: 'Login Successfull',
    OPPS: 'Opps... Something went wrong!',
    INVALID_PASSPHRASE: 'Invalid seed. Make sure your seed is correct, or create new wallet.',
    WALLET_CREATED_SUCCESFULLY: 'Wallet created successfully',
    LOGOUT_SUCCESSFULL: 'Logout Successfull',
    WALLET_LOCKED: 'Wallet Locked Successfully',
    PRIV_KEY_IMPORTED: 'Private Key Imported Successfully!',
    PRIV_KEY_NOT_IMPORTED: 'Private Key is not imported.',
    ADDED_TO: 'added to',
    SUCCESSFULLY: 'Successfully',
    COIN_SELECTION: 'Coin Selection',
    SELECTION_NOT_FOUND: 'Local coin list is not found',
    AWAITING_TX_RESP: 'Awaiting transaction data response',
  },
  COIN_WALLETS: {
    TX_FAILED: 'Transaction Failed',
    TX_SUCCESS: 'Transaction Successful',
    TX: 'Transaction',
  },
  IAPI: {
    PUBLIC_SM: 'public',
    CON_STATUS: 'Connection status',
  },
  KMD_NATIVE: {
    SELECT_ADDRESS: 'Select Transparent or Private Address',
    SELECT_ADDRESS_ALT: 'Select Transparent or Private KMD Address',
    PRIVATE: 'private',
    NEW_ADDR_GENERATED: 'New address generated successfully',
    QUEUED: 'Queued',
    PLEASE_REFRESH: 'Please press refresh button in a minute or so to see updated status',
    EXECUTING: 'Executing',
    FAILED: 'Failed',
    SUCCESS: 'Success',
    MESSAGE: 'Message',
    EXECUTION_SECONDS: 'Execution Seconds',
    WAIT_UNTIL_SYNCED: 'Transaction history is unavailable during synchronization progresss',
    TXID: 'Transaction ID',
    ZCASH_PARAMS_MISSING: 'Zcash params are missing or incomplete:',
    ZCASH_PARAMS_MISSING_ROOT_DIR: '- missing root folder',
    ZCASH_PARAMS_MISSING_PROVING_KEY: '- missing proving key',
    ZCASH_PARAMS_MISSING_VERIFYING_KEY: '- missing verifying key',
    ZCASH_PARAMS_MISSING_PROVING_KEY_SIZE: '- proving key size is incorrect',
    ZCASH_PARAMS_MISSING_VERIFYING_KEY_SIZE: '- verifying key size is incorrect',
  },
  LOGIN: {
    QMENU_REMOVE_SPV: 'Remove all SPV coins',
    ERR_SEED_STORAGE: 'Seed storage error',
    CUSTOM_PIN_FNAME: 'Custom pin file name',
    CUSTOM_PIN_FNAME_INFO: 'Pin file name can only contain alphanumeric characters, dash "-" and underscore "_"',
    FIRST_TIME_SEED_USE: 'First time seed use',
    PLEASE_WRITE_DOWN_YOUR_PUB: 'Please write down your public address, logout and login into Agama again to verify that your seed is correct.',
    YOUR_ADDR_APPEARS_CORRECT: 'Your seed appears to be correct. As a final check up please double check that the public address you wrote down earlier is matching the one you see right now.',
    CONGRATS_ALL_SET: 'Congrats, you are all set!',
    YOUR_SEED_DOESNT_SEEM_CORRECT: 'Your seed doesn\'t seem to be correct. Please logout and repeat wallet creation procedure again.',
    SEED_VERIFICATION_ERROR: 'Seed verification error!',
    ENCRYPTION_KEYS_DONT_MATCH: 'Encryption keys don\'t match',
    ENCRYPTION_KEY_EMPTY: 'Encryption key/confirmation field is empty',
    SEED_ENCRYPT: 'Seed encrypt',
    SEED_ENCRYPT_KEY_CONFIRM: 'Seed encrypt key confirm',
    SEED_ENCRYPTION_WEAK_PW: 'Encryption key/password is weak, please choose a stronger password',
    WEAK_PW: 'Weak password detected',
    SEED_TRAILING_CHARS: 'Your seed contains leading/trailing space characters',
    PIN_PW_ACCESS: 'Pin / password access',
    SEED_ENCRYPT_KEY_DESC_P1: 'Your seed is going to be stored locally and encrypted with a key/password.',
    SEED_ENCRYPT_KEY_DESC_P2: 'This option aims to minimize typos in seed keying and multiple seeds case scenario.',
    SEED_ENCRYPT_KEY_OLD: 'Old seed encrypt key (PIN)',
    SEED_ENCRYPT_KEY: 'Seed encrypt key (PIN)',
    SEED_ENCRYPT_KEY_NEW: 'New seed encrypt key (PIN)',
    SEED_ENCRYPT_KEY_CONFIRM_NEW: 'New seed encrypt key confirm',
    SEED_ENCRYPT_KEY_CONF: 'Seed encrypt key confirm',
    SEED_ENTROPY_CHECK_P1: 'Your seed is weak, it means that someone can steal your funds by guessing/bruteforcing the seed.',
    SEED_ENTROPY_CHECK_P2: 'Consider creating a stronger seed and moving your funds to a new address.',
    SEED_ENTROPY_CHECK_P3: 'Consider using a stronger seed that is not susceptible to such attacks.',
    SEED_ENTROPY_CHECK_TITLE: 'Weak seed detected',
    SEED_ENTROPY_CHECK_LOGIN_P1: 'Your seed is weak, it means that someone can steal your funds by guessing/bruteforcing the seed.',
    SEED_ENTROPY_CHECK_LOGIN_P2: 'Consider creating a stronger seed and moving your funds to a new address.',
    QR_UNABLE_TO_DECODE: 'Unable to recognize QR code',
    QR_ERROR: 'QR scan Error',
    SEED_QR_RECOVERY: 'Seed QR recovery',
    SPV_MODE_DESC_P1: 'If you need a quick and easy access to your funds try',
    SPV_MODE_DESC_P2: 'Lite (SPV) mode',
    SPV_MODE_DESC_P3: 'which doesn\'t require any blockchain to be loaded locally.',
    SPV_MODE_DESC_P4: 'All data is requested on demand from Electrum servers.',
    NATIVE_MODE_DESC_P1: 'Be aware:',
    NATIVE_MODE_DESC_P2: 'Native mode',
    NATIVE_MODE_DESC_P3: 'requires to download the whole blockchain data to a local disk before you can start using it.',
    NATIVE_MODE_DESC_P4: 'This may take from',
    NATIVE_MODE_DESC_P5: 'several hours to a day',
    NATIVE_MODE_DESC_P6: 'depending on your connection and hardware.',
    NATIVE_MODE_DESC_P7: 'Please',
    NATIVE_MODE_DESC_P8: 'try to keep Agama running',
    NATIVE_MODE_DESC_P9: 'until the whole process is finished.',
    OR_USE_A_SHORTCUT: 'or use a shortcut',
    PIN_LOGIN_INFO: 'You can login by entering a login seed or by selecting a pin',
    QUICK_ACCESS: 'Quick access',
    PWD_REQ: 'Password is required.',
    WALLET_SEED_REQ: 'Wallet seed is required.',
    SAVED_WALLET_SEED: 'Have you saved your wallet seed?',
    SEED_MAKE_SURE_BACKUP: 'Make sure you have it backed up. Without this seed you won\'t be able to access your wallet in the future!',
    YES_I_BACKUP: 'Yes, I have taken backup.',
    WALLET_LOCKED_LOGIN: 'Wallet Locked. Please login.',
    CANCEL: 'Cancel',
    UNLOCK: 'Unlock',
    SIGN_IN: 'Sign In',
    WELCOME: 'Welcome',
    ENTER_VALUE_AGAIN: 'Please enter the same value again',
    CUSTOM_WALLET_SEED: 'Custom wallet seed',
    MUST_ENTER_SEED: 'You must enter a seed',
    INVALID_SEED: 'Invalid Seed',
    SEED_NOT_OF_TYPE: 'The inserted seed is not of type',
    IGUANA_SEED: 'Iguana (256 bits)',
    WAVES_SEED: 'Waves',
    NXT_SEED: 'NXT',
    SEED_COPIED: 'Seed copied',
    SEED_SUCCESSFULLY_COPIED: 'The seed was successfully copied',
    ENCRYPT_SEED: 'Encrypt seed',
    PUBKEY: 'pubkey',
    ENCRYPT_KEY: 'Encrypt key',
    DECRYPT_KEY: 'Password',
  },
  SIDEBAR: {
    EDEX_MOTTO: 'Most Secure, Easy and Native Decentralised Exchange',
    JUMBLR_MOTTO: 'Secure, Native and Decentralised Coin Anonymizer',
  },
  SUPPORT: {
    FOR_GUIDES: 'For guides & FAQ please navigate to',
    TO_SEND_FEEDBACK_P1: 'For Feedback please open a ticket',
    TO_SEND_FEEDBACK_P2: 'or send an email to support@komodoplatform.com',
  },
  SETTINGS: {
    SWEEP_PROCESSING_TX: 'Processing transaction...',
    SWEEP_LOADING_BALANCE: 'Fetching balance...',
    FROM_SM: 'from',
    SWEEP_SUCCESS: '@template@ sent from',
    IS_EMPTY: '@template@ is empty',
    UNABLE_TO_FETCH_BALANCE: 'Unable to fetch @template@ balance',
    SWEEP_WARNING: 'this operation is irreversible!',
    SWEEP_CONF: 'Are you sure you want to continue?',
    SWEEP_KEY_DESC: 'This section allows you to sweep (spend) funds from your priv key/seed',
    SWEEP_KEY: 'Sweep keys',
    ADDRESS_BOOK_SAVED: 'Address book is saved',
    SAVE: 'Save',
    TITLE: 'Title',
    COIN: 'Coin',
    ADDRESS_BOOK: 'Address book',
    RENAME_PIN: 'Rename .pin file',
    CHANGE_PIN: 'Change pin (encryption key)',
    DOWNLOAD_KV_ELECTRUMS_DONE: 'KV Electrum servers list is downloaded. Please restart the app.',
    DOWNLOAD_KV_ELECTRUMS_ERR: 'Unable to retrieve remote KV Electrum servers list',
    DOWNLOAD_KV_ELECTRUMS: 'Download KV Electrum servers list',
    CURRENT_CACHE_SIZE: 'Current cache size',
    CLEAR_CACHE: 'Clear cache',
    PIN_RENAMED: 'Pin @template@ renamed',
    PIN_REMOVED: 'Pin @template@ is deleted',
    OLD_PIN_NAME: 'Old pin name',
    NEW_PIN_NAME: 'New pin name',
    PIN_NAME: 'Pin name',
    PINS_LIST: 'Pins list',
    PIN_REMOVE_CONFIRM: 'Are you sure you want to remove @template@?',
    ENTRY_REMOVE_CONFIRM: 'Are you sure you want to remove entry @template@?',
    IS_UNREACHABLE: 'is unreachable',
    SPV_SERVER: 'SPV server',
    SPV_SERVER_SET_TO: 'SPV server set to',
    ENCRYPT: 'Encrypt',
    THIS_SECTION_ALLOWS_YOU_TO_ENCRYPT: 'This section allows you to encrypt a seed with a password and store it locally.',
    THIS_SECTION_ALLOWS_YOU_TO_MANAGE_ADDRESS_BOOK: 'This section allows you to manage an address book',
    CREATE_NEW_ENTRY: 'Create new entry',
    ENCRYPT_SEED: 'Encrypt seed',
    SEED_IS_COPIED: 'Seed is copied to clipboard',
    GET_SEED_AND_WIF: 'Get seed and WIF keys',
    PW_PIN: 'Password / pin',
    OR_WIF_FORMAT: 'or WIF key format',
    DAEMON_PORTS: 'Daemon ports',
    KEY_IS_NOT_FOUND: 'Key is not found',
    ADDRESSES_SM: 'addresses',
    ACCOUNT_SM: 'account',
    ACCOUNTS_SM: 'accounts',
    GET_KEY: 'Get key',
    DATADIR_DELETE_PROMPT: 'Are you sure you want to clear @template@ data folder?',
    YES: 'Yes',
    NO: 'No',
    KEEP: 'Keep',
    DELETE: 'Delete',
    COIND_DELETING: 'Deleting @template@ data..',
    COIND_DATADIR_CLEAR_P1: 'Warning: the following form will wipe out all native coin data!',
    COIND_DATADIR_CLEAR_P2: 'Don\'t touch anything if you\'re not sure what you\'re doing.',
    GET_KEYS: 'Get keys',
    FETCHING_KEYS: 'Fetching keys',
    SEARCH_KEY_PATTERN: 'Search key pattern',
    ADDRESS: 'Address',
    KEYS_SM: 'keys',
    FOUND: 'Found',
    PICK_A_COIN: 'Pick a coin',
    CLEAR_NATIVE_DATADIR: 'Clear native coin data dir',
    KEYS_SM: 'keys',
    KEYS_CAP: 'Keys',
    BIP39_DISC: 'Hardware wallets disclaimer: by using this form you\'re acknowledging risks of exposing your seed',
    BIP39_DESC_P1: 'Description: the form below is going to search for a pub key depending on a range of key path combinations is chosen (No of accounts * account address path depth).',
    BIP39_DESC_P2: 'The app might temporary freeze for several seconds during search procedure.',
    SHOW_APP_RUNTIME_LOG: 'Show app runtime log',
    WRONG_PASSPHRASE: 'Wrong seed',
    SPV_SERVER_LIST_DESC: 'Server list selection is only available for active coins that have more than 1 server to connect to.',
    SPV_SERVERS: 'SPV servers list',
    SPV_SINGLE_SERVER_NOTICE: 'There is only one electrum server available. SPV verification is coming from the same server providing all remote data.',
    KMD_MAIN_SYNC_ONLY: 'KMD main sync only',
    RPC_FETCH_ONLY_DESC: 'Fetch block synchronization data only. Skip any other requests that can deteriorate sync speed.',
    RESET_TO_DEFAULT: 'Reset to default',
    PROGRESS: 'Progress',
    SUPPORT: 'Support',
    SUPPORT_TICKETS: 'Support tickets',
    GET_DISCORD_INVITE: 'Get Discord invite',
    ADDRESS_LIST: 'Address',
    WIF_KEY_LIST: 'WIF (Wallet Import Format) key',
    CLI_RESPONSE: 'CLI response',
    PASSPHRASE_REQ: 'Seed is required.',
    SAVE_APP_CONFIG: 'Save app config',
    CONFIG_RESTART_REQUIRED: 'Any changes to app config require app restart!',
    APP_CONFIG: 'App Config',
    APP_INFO: 'App Info',
    APP_RELEASE: 'App Release',
    NAME: 'Name',
    VERSION: 'Version',
    SYS_INFO: 'System Info',
    ARCH: 'Architecture',
    OS_TYPE: 'OS Type',
    OS_PLATFORM: 'OS Platfrom',
    OS_RELEASE: 'OS Release',
    CPU: 'CPU',
    CPU_CORES: 'CPU Cores',
    MEM: 'Memory',
    LOCATIONS: 'Locations',
    LOCATION: 'Location',
    CACHE: 'Cache',
    CONFIG: 'Config',
    BIN: 'Bin',
    DIR: 'Dir',
    ADD_PEER_IP: 'Add Peer IP',
    APP_SESSION: 'App Session',
    EXPORT_KEYS_NOTE: 'Note: it\'s important that you provide the same seed you used to login to the wallet!',
    EXPORT_KEYS_NOTE_PIN: 'Note: it\'s important that you provide the same password/pin you used to login to the wallet!',
  },
  TX_INFO: {
    ADDRESS: 'address',
    AMOUNT: 'amount',
    CATEGORY: 'category',
    CONFIRMATIONS: 'confirmations',
  },
  ZCPARAMS_FETCH: {
    DOWNLOADING_ZCASH_KEYS: 'Downloading Zcash keys',
    BOTH_KEYS_VERIFIED: 'Both Zcash param keys are downloaded and verified!',
    CLOSE_THE_MODAL: 'Close the modal and try to add a coin again.',
    ZCPARAMS_VERIFICATION_ERROR_P1: 'Zcash param',
    ZCPARAMS_VERIFICATION_ERROR_P2: 'verification error!',
    ZCPARAMS_FETCH: 'ZCash Params Fetch',
    SELECT_ZCPARAMS_SOURCE: 'Select resource to download Zcash params keys from',
    DOWNLOAD: 'Download',
  },
  SEND: {
    USE_ZMERGETOADDRESS: 'Merge funds (z_mergetoaddress)',
    ANY: 'Any address(es)',
    ANY_TADDR: 'Any transparent address(es)',
    ANY_ZADDR: 'Any z address(es)',
    ALL_OPID_CLEARED: 'All Z transaction(s) traces are cleared!',
    CLEAR_ALL: 'Clear all',
    CLEAR_ALL_DESC: 'For maximum privacy it\'s advised to clear all traces of your outgoing z transactions including runtime data.<br>If you want this action to take place automatically see Settings/App config section.',
    SELECT_ADDRESS: 'Select an address',
    INVALID_Z_ADDRESS: 'Invalid Z address',
    ENTER_Z_ADDR: 'Enter Z address',
    COIN_CONTROL: 'Coin control',
    NO_VALID_UTXO_ERR: 'No valid UTXO is available. Your previous transaction is still in unconfirmed state. Please retry later.',
    PIN_NUMBER: 'Pin number',
    ENTER_YOUR_PIN: 'Enter your pin number to confirm transaction',
    CLOCK_OUT_OF_SYNC: 'Your local clock is not set properly. This will prevent sending a KMD transaction.',
    FEE_PER_BYTE: 'Fee per byte',
    PER_KB: 'per KB',
    ESTIMATED_TO_BE_INCLUDED_P3: 'block',
    ESTIMATED_TO_BE_INCLUDED_P2: 'blocks',
    ESTIMATED_TO_BE_INCLUDED_P1: 'Estimated to be included within the next',
    CONF_TIME_WITHIN_60_MIN: 'within 60 min',
    CONF_TIME_WITHIN_3O_MIN: 'within 30 min',
    CONF_TIME_LESS_THAN_30_MIN: 'within less than 30 min',
    FETCHING_BTC_FEES: 'Fetching BTC fees',
    CONF_TIME: 'Confirmation time',
    ADVANCED_SELECTION: 'Advanced selection',
    BTC_FEES_DESC_P1: 'Electrum based fee estimates may not be as accurate as bitcoinfees.earn.com.',
    BTC_FEES_DESC_P1: 'It is advised to use fast/average/slow options if you want your transaction to be confirmed within 60 min time frame.',
    BTC_FEES_DESC_P3: 'Estimates are based on bitcoinfees.earn.com data.',
    BTC_FEES_DESC_P4: 'Around 90% probability for a transaction to be confirmed within desired time frame.',
    VALIDATION_IS_NOT_VALID_ADDR_P1: 'is not a valid',
    VALIDATION_IS_NOT_VALID_ADDR_P2: 'pub address',
    CANT_GET_BTC_FEES: 'Cannot get BTC fees',
    YOUR_TXHISTORY_CONTAINS_ZTX_P1: 'Your history contains shielded transactions(z).',
    YOUR_TXHISTORY_CONTAINS_ZTX_P2: 'Please move funds to another transparent address in order to use Lite mode.',
    FEE: 'Fee',
    TO: 'to',
    TOTAL_AMOUNT_DESC: 'Total (amount + transaction fee)',
    KMD_INTEREST: 'KMD rewards',
    ADJUSTED_AMOUNT: 'Adjusted amount',
    MAX_AVAIL_AMOUNT_TO_SPEND: 'Max. available amount to spend - transaction fee',
    SATS: 'sats',
    SELF: 'Self',
    ALL: 'All',
    BAD_TXN_SPENT_ERR1: 'This particular error can happen in the following cases:',
    BAD_TXN_SPENT_ERR2: 'Your machine\'s clock is not set properly',
    BAD_TXN_SPENT_ERR3: 'SPV server is temporary out of sync. Try to switch over to another one.',
    BAD_TXN_SPENT_ERR4: 'Double spend in case you just made another transaction',
    MIN_AMOUNT_IS: 'min @template@ amount is',
    AMOUNT_IS_TOO_SMALL: 'Amount @template@ is too small',
    MAX_AVAIL_BALANCE: 'max available balance is',
    TXID_COPIED: 'TXID copied to clipboard',
    RESULT: 'Result',
    PROCESSING_TX: 'Processing transaction',
    TRANSACTION_ID: 'Transaction ID',
    SUCCESS_SM: 'success',
    WARNING: 'Warning',
    WARNING_SPV_P1: 'your wallet data is verified only by a single server!',
    WARNING_SPV_P2: 'If you still want to continue press "Confirm".',
    SPV_VERIFYING: 'Verifying transaction data',
    PROCESSING_REQ: 'Processing requests',
    LOCKED_PLEASE_WAIT: 'Locked, please wait',
    UPDATE: 'Update',
    SELECT_T_OR_Z_ADDR: 'Select Transparent or Private Address',
    ENTER_T_OR_Z_ADDR: 'Enter Transparent or Private address',
    ENTER_ADDRESS: 'Enter address',
    AWAITING: 'Awaiting in queue',
    PROCESSING: 'Processing',
    ERROR_CODE: 'Error Code',
    WAITING: 'Waiting',
    PROCESSING_TRANSACTION: 'Processing transaction',
    NOTE_IT_WILL_TAKE: 'Note: it may take a few minutes to complete the transaction',
    ENTER_AN_ADDRESS: 'Enter an address',
    YOU_PICKED_OPT: 'You picked option',
    PLEASE_WAIT: 'Please wait',
    SEND_TO_ADDRESS_MIN_LENGTH: 'Send to address must be at least 34 characters long',
    AMOUNT_POSITIVE_NUMBER: 'Amount must be a positive number',
    FEE_POSITIVE_NUMBER: 'Fee must be a positive number',
    TOTAL_AMOUNT_POSITIVE_NUMBER: 'Total amount (amount - fee) must be a positive number',
    INSUFFICIENT_FUNDS: 'You don\'t have the necessary funds to make this transaction',
    SELECT_SOURCE_ADDRESS: 'Select source (from) address',
    QR_COIN_MISMATCH_MESSAGE_IMPORT_COIN: 'QR code had coin ',
    QR_COIN_MISMATCH_MESSAGE_ACTIVE_COIN: '. You have ',
    QR_COIN_MISMATCH_MESSAGE_END: ' active in your wallet. Please, check that you have same coin active that you try to import!',
    QR_COIN_MISMATCH_TITLE: 'Coin Mismatch',
    SEND_NATIVE_SYNC_WARNING: 'Your wallet is not fully synced! Please wait until it reached 100% to avoid possible transaction send implications.',
    WARNING_FEE_EXCEEDS_DEFAULT_THRESHOLD: 'Provided fee exceeds default fee @template@ times!',
  },
  FIAT_CURRENCIES: {
    AUD: 'Australian Dollar',
    BRL: 'Brazilian Real',
    GBP: 'British Pound',
    BGN: 'Bulgarian Lev',
    CAD: 'Canadian Dollar',
    HRK: 'Croatian Kuna',
    CZK: 'Czech Koruna',
    CNY: 'Chinese Yuan',
    DKK: 'Danish Krone',
    EUR: 'Euro',
    HKD: 'Hong Kong Dollar',
    HUF: 'Hungarian Forint',
    INR: 'Indian Rupee',
    IDR: 'Indonesian Rupiah',
    ILS: 'Israeli Shekel',
    JPY: 'Japanese Yen',
    KRW: 'Korean Won',
    MYR: 'Malaysian Ringgit',
    MXN: 'Mexican peso',
    NZD: 'New Zealand Dollar',
    NOK: 'Norwegian Krone',
    PHP: 'Philippine Peso',
    PLN: 'Polish Zloty',
    RON: 'Romanian Leu',
    RUB: 'Russian Ruble',
    SGD: 'Singapore Dollar',
    ZAR: 'South African Rand',
    SEK: 'Swedish Krona',
    CHF: 'Swiss Franc',
    THB: 'Thai Baht',
    TRY: 'Turkish Lira',
    USD: 'US Dollar',
  },
  ASSETCHAINS: {
    BET: 'BET',
    BOTS: 'BOTS',
    CEAL: 'CEAL NET',
    COQUI: 'COQUI',
    KMDICE: 'KMDICE',
    CHAIN: 'Chainmakers',
    GLXT: 'GLXToken',
    EQL: 'Equaliser',
    CRYPTO: 'CRYPTO',
    HODL: 'HODL',
    DEX: 'DEX',
    JUMBLR: 'JUMBLR',
    KV: 'KV',
    MGW: 'MultiGateway',
    MVP: 'MVP Lineup',
    MNZ: 'Monaize',
    PANGEA: 'PANGEA',
    REVS: 'REVS',
    MSHARK: 'MSHARK',
    MESH: 'SpaceMesh',
    SUPERNET: 'SUPERNET',
    WLC: 'WIRELESS',
    AXO: 'AXO',
    ETOMIC: 'ETOMIC',
    BTCH: 'BTCH',
    BEER: 'BEER (Test coin)',
    PIZZA: 'PIZZA (Test coin)',
    VOTE2018: 'VOTE2018 (Notary Elections)',
    NINJA: 'NINJA',
    GLXT: 'GLXToken',
    BNTN: 'Blocnation',
    PRLPAY: 'Pearl Pay',
    OOT: 'Utrum',
    ZILLA: 'ChainZilla',
    DSEC: 'DevSec',
    VRSC: 'VerusCoin',
  	MGNX: 'MagnaX',
    CALL: 'Capital',
    CCL: 'CoinCollect',
    PIRATE: 'Pirate',
    KOIN: 'Koinon Coin',
    DION: 'DionPay',
    PTX: 'PatentTX',
  },
  CRYPTO: {
    STRAT: 'Stratis',
    TOA: 'TOA',
    USC: 'UltimateSecureCash',
    VPN: 'VpnCoin',
    WC: 'WinCoin',
    NRG: 'Energi',
    ABY: 'ArtByte',
    VOT: 'VoteCoin',
    BDL: 'Bitdeal',
    BTCP: 'BitcoinPrivate',
    MAC: 'Machinecoin',
    XWC: 'Whitecoin',
    XVC: 'Vcash',
    SMART: 'Smartcash',
    CRAVE: 'Crave',
    ACC: 'AdCoin',
    AC: 'AsiaCoin',
    AUR: 'Auroracoin',
    BCA: 'Bitcoin Atom',
    CLAM: 'Clams',
    CLUB: 'ClubCoin',
    DMD: 'Diamond',
    EXCL: 'ExclusiveCoin',
    FTC: 'FeatherCoin',
    FLASH: 'Flash',
    NLG: 'Gulden',
    LCC: 'Litecoin Cash',
    MNX: 'MinexCoin',
    NAV: 'NavCoin',
    NEOS: 'NeosCoin',
    OK: 'OKCash',
    OMNI: 'OmniLayer',
    PIVX: 'Pivx',
    RDD: 'Reddcoin',
    UNO: 'Unobtanium',
    XVG: 'Verge',
    VIVO: 'VIVO',
    EFL: 'E-Gulden',
    GBX: 'GoByte',
    BSD: 'Bitsend',
    LBC: 'LBRY Credits',
    ERC: 'Europecoin',
    BATA: 'Bata',
    EMC2: 'Einsteinium',
    SYS: 'Syscoin',
    IOP: 'Internet of People',
    ZEN: 'Zencash',
    XZC: 'Zcoin',
    FJC: 'Fujicoin',
    GAME: 'GameCredits',
    BCBC: 'Bitcoin CBC',
    BTG: 'BitcoinGold',
    BCH: 'BitcoinCash',
    BTC: 'Bitcoin',
    DASH: 'Dash',
    DNR: 'Denarius',
    DGB: 'DigiByte',
    FAIR: 'Faircoin',
    ARG: 'Argentum',
    LTC: 'Litecoin',
    MONA: 'Monacoin',
    NMC: 'Namecoin',
    VTC: 'Vertcoin',
    VIA: 'Viacoin',
    SIB: 'Sibcoin',
    BLK: 'Blackcoin',
    DOGE: 'Dogecoin',
    ZEC: 'Zcash',
    HUSH: 'Hush',
    SNG: 'SnowGem',
    ZCL: 'Zclassic',
    XMY: 'Myriad',
    GRS: 'Groestlcoin',
    HODLC: 'Hodl coin',
    BTX: 'Bitcore',
    QTUM: 'Qtum',
    BTCZ: 'BitcoinZ',
    KMD: 'Komodo',
    CHIPS: 'Chips',
    MZC: 'Mazacoin',
    ZET: 'Zetacoin',
    SLR: 'Solarcoin',
    SMLY: 'Smileycoin',
    RBY: 'Rubycoin',
    VOX: 'RevolutionVR',
    PUT: 'PutinCoin',
    POT: 'Potcoin',
    POSW: 'Poswcoin',
    PINK: 'Pinkcoin',
    PSB: 'Pesobit',
    NSR: 'NuShares',
    NVC: 'Novacoin',
    NYC: 'NewYorkCoin',
    NRO: 'Neuro',
    LYNX: 'Lynx',
    LINX: 'Linx',
    LDCN: 'Landcoin',
    KOBO: 'Kobocoin',
    IXC: 'Ixcoin',
    INSN: 'InsaneCoin',
    THC: 'Hempcoin',
    HNC: 'Helleniccoin',
    GRC: 'Gridcoin',
    GCR: 'Global Currency Reserve',
    FRST: 'FirstCoin',
    ERC: 'Europecoin',
    EDRC: 'EDRcoin',
    ECN: 'eCoin',
    DGC: 'Digitalcoin',
    DEFC: 'Defcoin',
    CMP: 'CompCoin',
    CCN: 'Cannacoin',
    CDN: 'Canada eCoin',
    BRIT: 'BritCoin',
    XBC: 'BitcoinPlus',
    BELA: 'BelaCoin',
    USNBT: 'NuBits',
    ONX: 'Onixcoin',
    ZET: 'Zetacoin',
    JBS: 'Jumbucks',
    SLM: 'Slimcoin',
    AXE: 'Axe',
    PPC: 'Peercoin',
    MZC: 'Mazacoin',
    SDC: 'ShadowCash',
  },
  TOOLS: {
    TOOLS: 'Tools',
    OFFLINE_SIG_CREATE: 'Offline signing create',
    OFFLINE_SIG_SCAN: 'Offline signing scan',
    STR_TO_QR: 'String to QR',
    SEED_TO_KP: 'Seed to key pair',
    SEED_TO_KP_ALT: 'Seed to key pair (wif, pub)',
    WIF_TO_WIF: 'WIF to WIF',
    WIF_TO_WIF_ALT: 'WIF to key pair (wif, pub)',
    ADDR_VER_CHECK: 'Address version check',
    BALANCE: 'Balance',
    SPLIT: 'Split',
    MERGE: 'Merge',
    SPV_NATIVE: '* Electrum, ** Native',
    ERR_GET_BALANCE: 'Get balance error',
    ERR_GET_UTXO: 'Get UTXO error',
    ERR_MERGE_UTXO: 'Merge UTXO error',
    ERR_SEED_TO_WIF: 'Seed to wif error',
    ERR_OFFLINE_TX_SIG: 'Offline tx signing error',
    ERR_CANT_ENCODE_QR_LARGE_TX: 'can\'t encode a qr tx larger than 3 utxos!',
    ERR_SPLIT_UTXO: 'Split UTXO error',
    UTXO_SPLIT_NOOP: 'no op, output is bigger than utxo size!',
    GET_BALANCE: 'Get balance',
    COIN: 'Coin',
    ADDR: 'Address',
    BALANCE_CONF: 'Balance (confirmed)',
    BALANCE_UNCONF: 'Balance (unconfirmed)',
    AMOUNT: 'Amount',
    CONFS: 'Confirmations',
    VOUT: 'Vout',
    GET_UTXO_LIST: 'Get UTXO list',
    GET_UTXO: 'Get UTXO(s)',
    MERGE_SUCCESS: 'Merge success',
    NO_VALID_UTXO: 'No valid UTXO',
    SEED: 'Seed',
    ENTER_A_SEED: 'Enter a seed',
    TOTAL: 'Total',
    SHOW_UTXO_LIST: 'Show UTXO list',
    UTXO_COUNT_TO_MERGE: 'UTXO count to merge in 1 tx',
    UTXO_COUNT: 'UTXO count',
    MERGE_UTXO: 'Merge UTXO(s)',
    OFFLINE_TX_SIG: 'Offline Transaction Signing',
    GEN_UNSIG_TX_QR: 'Generate unsigned tx QR',
    QR_PAYLOAD: 'QR payload',
    CLOSE: 'Close',
    PUSH_QR_TX: 'Push QR transaction',
    TX_PUSHED: 'transaction pushed',
    ERROR: 'Error',
    PUB_ADDR_VER_CHECK: 'Pub address version check',
    PUB_ADDR: 'Pub address',
    ENTER_A_PUB_ADDR: 'Enter a pub address',
    CHECK_VERSION: 'Check version',
    VERSION: 'Version',
    COINS: 'Coin(s)',
    IGUANA_COMPAT: 'Iguana Core / Komodo ICO compatible',
    GET_WIF: 'Get WIF',
    SPLIT_SUCCESS: 'Split success',
    SPLIT_UTXO: 'Split UTXO',
    LARGEST: 'Largest',
    UTXO_SIZES: 'UTXO sizes',
    NUMBER_OF_PAIRS: 'Number of pairs',
    CALC_TOTAL_OUT_SIZE: 'Calc total output size',
    TOTAL_OUT_SIZE: 'Total out size',
    TYPE_A_STR: 'Type a string here',
    ENTER_A_WIF: 'Enter a WIF',
    GET_WIF: 'Get WIF',
    GET_BALANCE_MULTI_KMD: 'This section doesn\'t account for KMD rewards. It shows multiple balances only.',
    ADDRESSES: 'Addresses',
    ADDRESS_MULTI: 'Enter KMD pub addresses each address on a new line.',
    REMOTE_CALL_EXPLORER_ACKNOWLEDGEMENT: 'Privacy notification: this is a remote call to KMD explorer servers.',
    ALL_BALANCES_ARE_EMPTY: 'All balances are empty',
  },
  KV: {
    TAG: 'Tag',
    TITLE: 'Title',
    CONTENT: 'Content',
    SEND_KV: 'Send KV',
    SEND_TX: 'Send transaction',
    CHARS_LEFT: 'Chars left',
    KV_ERR_TOO_LONG: 'Content is too long! Max 4096 chars.',
    ENTER_A_TITLE: 'Enter a title',
    ENTER_A_TAG: 'Enter a tag',
    KV_VIEW: 'KV view',
    TX_VIEW: 'Transactions view',
    KV_HISTORY: 'KV history',
  },
  DEX: {
    GEN_NEW_PASSPHRASE: 'Generate a new seed',
    LOGIN: 'Login',
    BACKUP_PASSPHRASE_P1: 'Backup your seed',
    BACKUP_PASSPHRASE_P2: 'it can\'t be retrieved!',
    ESTIMATED_BALANCE: 'Estimated balance',
    TRADE_HISTORY_SM: 'trade history',
    ELECTRUM_MODE: 'Electrum mode',
    NATIVE_MODE: 'Native mode',
  },
  LANG: {
    EN: 'English',
    DE: 'Deutch',
  },
  FIAT_CURRENCIES: {
    AUD: 'Australian Dollar (AUD)',
    BRL: 'Brazilian Real (BRL)',
    GBP: 'British Pound (GBP)',
    BGN: 'Bulgarian Lev (BGN)',
    CAD: 'Canadian Dollar (CAD)',
    HRK: 'Croatian Kuna (HRK)',
    CZK: 'Czech Koruna (CZK)',
    CNY: 'Chinese Yuan (CNY)',
    DKK: 'Danish Krone (DKK)',
    EUR: 'Euro (EUR)',
    HKD: 'Hong Kong Dollar (HKD)',
    HUF: 'Hungarian Forint (HUF)',
    INR: 'Indian Rupee (INR)',
    IDR: 'Indonesian Rupiah (IDR)',
    ILS: 'Israeli Shekel (ILS)',
    JPY: 'Japanese Yen (JPY)',
    KRW: 'Korean Won (KRW)',
    MYR: 'Malaysian Ringgit (MYR)',
    MXN: 'Mexican peso (MXN)',
    NZD: 'New Zealand Dollar (NZD)',
    NOK: 'Norwegian Krone (NOK)',
    PHP: 'Philippine Peso (PHP)',
    PLN: 'Polish Zloty (PLN)',
    RON: 'Romanian Leu (RON)',
    RUB: 'Russian Ruble (RUB)',
    SGD: 'Singapore Dollar (SGD)',
    ZAR: 'South African Rand (ZAR)',
    SEK: 'Swedish Krona (SEK)',
    CHF: 'Swiss Franc (CHF)',
    THB: 'Thai Baht (THB)',
    TRY: 'Turkish Lira (TRY)',
    USD: 'US Dollar (USD)',
  },
  DICE: {
    DICE: 'Dice',
  },
};

export default LANG_EN;
