const kmdexplorer = {
  CHAIN: 'https://chain.kmdexplorer.io',
  OOT: 'https://oot.kmdexplorer.io',
  ETOMIC: 'https://etomic.kmdexplorer.io',
  BEER: 'https://beer.kmdexplorer.io',
  BTCH: 'https://btch.kmdexplorer.io',
  COQUI: 'https://coqui.kmdexplorer.io',
  BET: 'https://bet.kmdexplorer.io',
  BOTS: 'https://bot.kmdexplorer.io',
  CEAL: 'https://ceal.kmdexplorer.io',
  CRYPTO: 'https://crypto.kmdexplorer.io',
  DEX: 'https://dex.kmdexplorer.io',
  HODL: 'https://hodl.kmdexplorer.io',
  JUMBLR: 'https://jumblr.kmdexplorer.io',
  KV: 'https://kv.kmdexplorer.io',
  MESH: 'https://mesh.kmdexplorer.io',
  MGW: 'https://mgw.kmdexplorer.io',
  MSHARK: 'https://mshark.kmdexplorer.io',
  MVP: 'https://mvp.kmdexplorer.io',
  PANGEA: 'https://pangea.kmdexplorer.io',
  PIZZA: 'https://pizza.kmdexplorer.io',
  REVS: 'https://revs.kmdexplorer.io',
  SUPERNET: 'https://supernet.kmdexplorer.io',
  SHARK: 'https://shark.kmdexplorer.io',
  WLC: 'https://wlc.kmdexplorer.io',
  AXO: 'https://axo.kmdexplorer.io',
  DSEC: 'https://dsec.kmdexplorer.io',
  NINJA: 'https://ninja.kmdexplorer.io',
  GLXT: 'https://glxt.kmdexplorer.io',
  PRLPAY: 'https://prlpay.kmdexplorer.io',
  BNTN: 'https://bntn.kmdexplorer.io',
  EQL: 'https://eql.kmdexplorer.io',
  VRSC: 'https://vrsc.kmdexplorer.io',
  ZILLA: 'https://zilla.kmdexplorer.io',
  MGNX: 'http://mgnx.explorer.dexstats.info',
  CALL: 'https://call.explorer.mycapitalco.in',
  CCL: 'https://ccl.kmdexplorer.io',
  PIRATE: 'https://pirate.kmdexplorer.io',
  DION: 'https://explorer.dionpay.com',
};

export default kmdexplorer;